### ISSUE TITLE
Add dc:issued attribute to extensions registered with GBIF 

### ISSUE THREAD

**Issue by kbraak** [PlinianCore/Sources#2]
Yesterday the [GBIF extension XML schema definition](http://rs.gbif.org/schema/extension.xsd) was updated with a single change: a new required attribute called dc:issued has been added to the extension element. 

dc:issued is the date that the extension (version) was officially released.

Can you please update all PlinianCore extensions registered with GBIF to have a dc:issued attribute so that they are valid XML? 

For your convenience, the following extensions are currently registered with GBIF:

http://rs.gbif.org/sandbox/extension/external.json

Thanks,
Kyle

**Comment by santiagomtzdelariva** [comment]
Solved.
